services:
    admin_analytics.panel.hits:
        class: Admin\AnalyticsBundle\Panel\HitsPanel
        arguments:
            - "@templating"

    admin_analytics.settings.analytics:
        class: Admin\AnalyticsBundle\Settings\AnalyticsPanel
        tags:
            - { name: admin_base.settings_panel, alias: analytics }

    admin_analytics.twig.analytics:
        class: Admin\AnalyticsBundle\Twig\Extension\AnalyticsExtension
        arguments: ["@admin_base.settings_manager"]
        tags:
            - {name: twig.extension}
