Admin\CmsBundle\Entity\PublishedSection:
    type: entity
    table: admin_cms_published_section
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        page:
            type: string
        name:
            type: string
        content:
            type: text
