Admin\CmsBundle\Entity\Section:
    type: entity
    table: admin_cms_section
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: string
    manyToOne:
        version:
            targetEntity: Version
