Admin\CmsBundle\Entity\Version:
    type: entity
    repositoryClass: Admin\CmsBundle\Repository\VersionRepository
    table: admin_cms_version
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        title:
            type: string
        page:
            type: string
        published:
            type: boolean
    oneToMany:
        sections:
            targetEntity: Section
            mappedBy: version
