services:
    perform_media_player.crud.playlist:
        class: Perform\MediaPlayerBundle\Crud\PlaylistCrud
        tags:
            - {name: perform_base.admin, entity: "PerformMediaPlayerBundle:Playlist"}

    perform_media_player.crud.playlist_item:
        class: Perform\MediaPlayerBundle\Crud\PlaylistItemCrud
        tags:
            - {name: perform_base.admin, entity: "PerformMediaPlayerBundle:PlaylistItem"}

    perform_media_player.menu_link.playlist:
        class: Perform\MediaPlayerBundle\Menu\PlaylistLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: playlists }
