services:
    perform_media_player.crud.playlist:
        class: Perform\MediaPlayerBundle\Crud\PlaylistCrud
        tags:
            - {name: perform_base.crud, crud_name: "perform_media_player.playlist", route_name_prefix:"perform_mediaplayer_admin_"}

    perform_media_player.crud.playlist_item:
        class: Perform\MediaPlayerBundle\Crud\PlaylistItemCrud
        tags:
            - {name: perform_base.crud, crud_name: "perform_media_player.playlist_item"}

    perform_media_player.menu_link.playlist:
        class: Perform\MediaPlayerBundle\Menu\PlaylistLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: playlists }
