Perform\MusicBundle\Entity\Composition:
    type: entity
    table: perform_music_composition
    repositoryClass: Perform\MusicBundle\Repository\CompositionRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        title:
            type: string
        slug:
            type: string
            gedmo:
                slug:
                    separator: -
                    fields:
                        - title
        publishDate:
            type: datetime
        duration:
            type: integer
            nullable: true
        instruments:
            type: string
            nullable: true
        category:
            type: string
            nullable: true
        description:
            type: text
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        files:
            targetEntity: Perform\MediaBundle\Entity\File
            joinTable:
                name: perform_composition_file
    uniqueConstraints:
        slug:
            columns: [slug]
