services:
    _defaults:
        autowire: true
        public: true

    Perform\Tools\Documentation\FieldTypeReferenceGenerator:
        arguments:
            - '@twig'
            - '@perform_base.field_type_registry'
    Perform\Tools\Documentation\SassReferenceGenerator:

parameters:
    locale: en
    secret: docgen-kdjnskdjfnksjdfnk

security:
    encoders:
        Perform\UserBundle\Entity\User:
            algorithm: bcrypt
    providers:
        perform_bundles:
            entity:
                class: Perform\UserBundle\Entity\User
                property: email
    firewalls:
        main:
            anonymous: ~

framework:
    secret:          "%secret%"
    translator:      { fallbacks: ["%locale%"] }
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      true
    templating: false
    default_locale:  "%locale%"
    session:
        handler_id:  null
    fragments:       ~
    http_method_override: true
    assets:
        version_strategy: perform_base.asset_strategy

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        driver:   pdo_sqlite
        path: "%kernel.root_dir%/data.db"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sluggable: true

doctrine_cache:
    providers:
        default:
            namespace: docs
            file_system: []
