services:
    perform_blog.crud.markdown_post:
        class: Perform\BlogBundle\Crud\MarkdownPostCrud
        tags:
            - {name: perform_base.crud, crud_name: "perform_blog.markdown_post"}

    perform_blog.menu_link.blog:
        class: Perform\BlogBundle\Menu\BlogLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: blog }

    perform_blog.twig.blog:
        class: Perform\BlogBundle\Twig\Extension\BlogExtension
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }
