services:
    admin_blog.twig.blog:
        class: Admin\BlogBundle\Twig\Extension\BlogExtension
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }
