services:
    perform_blog.crud.markdown_post:
        class: Perform\BlogBundle\Crud\MarkdownPostCrud
        tags:
            - {name: perform_base.crud, crud_name: "perform_blog.markdown_post"}

    perform_blog.listener.menu:
        class: Perform\BlogBundle\EventListener\BlogMenuListener
        arguments:
            - '@perform_base.routing.crud_generator'
        tags:
            - { name: kernel.event_listener, event: perform_base.menu.build, method: onMenuBuild }

    perform_blog.twig.blog:
        class: Perform\BlogBundle\Twig\Extension\BlogExtension
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }
