Admin\Base\Entity\Setting:
    type: entity
    table: admin_base_setting
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        key:
            type: string
            column: key_name
        value:
            type: text
        defaultValue:
            type: text
            nullable: true
        type:
            type: string
        requiredRole:
            type: string
        global:
            type: boolean
    manyToOne:
        user:
            targetEntity: Admin\Base\Entity\User
            joinColumn:
                nullable: true
