Perform\Base\Entity\User:
    type: entity
    table: admin_base_user
    repositoryClass: Perform\Base\Repository\UserRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        forename:
            type: string
        surname:
            type: string
        password:
            type: string
        email:
            type: string
