services:
    perform_team.admin.team_member:
        class: Perform\TeamBundle\Admin\TeamMemberAdmin
        tags:
            - {name: perform_base.admin, entity: "PerformTeamBundle:TeamMember"}

    perform_team.menu_link.team:
        class: Perform\TeamBundle\Menu\TeamLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: team }
