services:
    admin_cms.block.html:
        class: Perform\CmsBundle\Block\HtmlBlockType
        tags:
            - {name: admin_cms.block_type, type: html}

    admin_cms.block.text:
        class: Perform\CmsBundle\Block\TextBlockType
        tags:
            - {name: admin_cms.block_type, type: text}
