services:
    admin_cms.listener.toolbar:
        class: Admin\CmsBundle\EventListener\ToolbarListener
        arguments:
            - "@twig"
            - "@admin_cms.twig.content"
            - "@doctrine.orm.entity_manager"
            - "@admin_cms.block_type_registry"
        tags:
            - {name: kernel.event_subscriber}

    admin_cms.menu_link.cms:
        class: Admin\CmsBundle\Menu\CmsLinkProvider
        tags:
            - {name: admin_base.link_provider, alias: cms}

    admin_cms.twig.content:
        class: Admin\CmsBundle\Twig\Extension\ContentExtension
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@twig"
        tags:
            - {name: twig.extension}

    admin_cms.warmer.gulp:
        class: Admin\CmsBundle\CacheWarmer\GulpSourcesWarmer
        arguments:
            - "@admin_cms.block_type_registry"
        tags:
            - {name: kernel.cache_warmer}

    admin_cms.publisher:
        class: Admin\CmsBundle\Publisher\Publisher
        arguments:
            - "@doctrine.orm.entity_manager"

    admin_cms.repo.version:
        class: Admin\CmsBundle\Repository\VersionRepository
        factory:
            - "@doctrine.orm.entity_manager"
            - "getRepository"
        arguments:
            - "AdminCmsBundle:Version"

    admin_cms.section_locator:
        class: Admin\CmsBundle\Locator\SectionLocator
        arguments:
            - "@admin_cms.repo.version"

    admin_cms.version_updater:
        class: Admin\CmsBundle\Updater\VersionUpdater
        arguments:
            - "@doctrine.orm.entity_manager"

    admin_cms.block_type_registry:
        class: Admin\CmsBundle\Block\BlockTypeRegistry

    admin_cms.block.html:
        class: Admin\CmsBundle\Block\HtmlBlockType
        tags:
            - {name: admin_cms.block_type, type: html}
