services:
    admin_cms.listener.toolbar:
        class: Admin\CmsBundle\EventListener\ToolbarListener
        arguments:
            - "@twig"
        tags:
            - {name: kernel.event_subscriber}

    admin_cms.menu_link.cms:
        class: Admin\CmsBundle\Menu\CmsLinkProvider
        tags:
            - {name: admin_base.link_provider, alias: cms}


    admin_cms.twig.content:
        class: Admin\CmsBundle\Twig\Extension\ContentExtension
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: twig.extension}

    admin_cms.publisher:
        class: Admin\CmsBundle\Publisher\Publisher
        arguments:
            - "@doctrine.orm.entity_manager"
