Perform\MediaPlayerBundle\Entity\PlaylistItem:
    type: entity
    table: perform_media_player_playlist_item
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        sortOrder:
            type: integer
    manyToOne:
        playlist:
            targetEntity: Playlist
            inversedBy: items
            joinColumn:
                nullable: false
        file:
            targetEntity: Perform\MediaBundle\Entity\File
            joinColumn:
                nullable: false
