services:
    admin_team.admin.team_member:
        class: Perform\Team\Admin\TeamMemberAdmin
        tags:
            - {name: admin_base.admin, entity: "PerformTeamBundle:TeamMember"}

    admin_team.menu_link.team:
        class: Perform\Team\Menu\TeamLinkProvider
        tags:
            - { name: admin_base.link_provider, alias: team }
