services:
    admin_team.admin.team_member:
        class: Admin\Team\Admin\TeamMemberAdmin
        tags:
            - {name: admin_base.admin, entity: "AdminTeamBundle:TeamMember", entityClass: "Admin\\Team\\Entity\\TeamMember"}
