Admin\Team\Entity\TeamMember:
    type: entity
    table: admin_team_team_member
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: string
        slug:
            type: string
            gedmo:
                slug:
                    separator: -
                    fields:
                        - name
        role:
            type: string
        description:
            type: text
        sortOrder:
            type: integer
            nullable: true
    uniqueConstraints:
        slug:
            columns: [slug]
