Admin\Team\Entity\TeamMember:
    type: entity
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: string
        role:
            type: string
        description:
            type: text
        sortOrder:
            type: integer
            nullable: true
