services:
    admin_base.admin.registry:
        class: Admin\Base\Admin\AdminRegistry
        arguments: ['@service_container']

    admin_base.doctrine.entity_resolver:
        class: Admin\Base\Doctrine\EntityResolver
        arguments: ['%admin_base.extended_entity_aliases%', '%admin_base.extended_entities%']

    admin_base.admin.user:
        class: Admin\Base\Admin\UserAdmin
        tags:
            - {name: admin_base.admin, entity: "AdminBaseBundle:User"}

    admin_base.routing.crud:
        class: Admin\Base\Routing\CrudLoader
        public: false
        arguments: ['@admin_base.admin.registry']
        tags:
            - {name: routing.loader}

    admin_base.routing.crud_url:
        class: Admin\Base\Routing\CrudUrlGenerator
        arguments: ['@admin_base.admin.registry', '@router']

    admin_base.listener.crud_template:
        class: Admin\Base\EventListener\CrudTemplateListener
        arguments: ['@service_container']
        tags:
            -
                name: kernel.event_listener
                event: kernel.controller
                method: onKernelController
                priority: -200

    admin_base.twig.crud:
        class: Admin\Base\Twig\Extension\CrudExtension
        arguments: ['@admin_base.routing.crud_url', '@admin_base.type_registry']
        tags:
            - {name: twig.extension}

    admin_base.menu_builder:
        class: Admin\Base\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }

    admin_base.menu_link.dashboard:
        class: Admin\Base\Menu\DashboardLinkProvider
        tags:
            - { name: admin_base.link_provider, alias: dashboard }

    admin_base.email.mailer:
        class: Admin\Base\Email\Mailer
        arguments: ["@swiftmailer.mailer", "@twig", "%admin_base.mailer.from_address%", "@logger"]

    admin_base.doctrine.user_listener:
        class: Admin\Base\Doctrine\UserListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber }
