Perform\EventsBundle\Entity\Event:
    type: entity
    table: perform_events_event
    repositoryClass: Perform\EventsBundle\Repository\EventRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        title:
            type: string
        slug:
            type: string
            gedmo:
                slug:
                    separator: -
                    fields:
                        - title
        startTime:
            type: datetime
        location:
            type: string
        description:
            type: text
        enabled:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    uniqueConstraints:
        slug:
            columns: [slug]
    manyToOne:
        image:
            targetEntity: Perform\MediaBundle\Entity\File
            joinColumn:
                nullable: true
