Admin\EventsBundle\Entity\Event:
    type: entity
    table: admin_events_event
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        title:
            type: string
        slug:
            type: string
            gedmo:
                slug:
                    separator: -
                    fields:
                        - title
        startTime:
            type: datetime
        location:
            type: string
        description:
            type: text
        enabled:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    uniqueConstraints:
        slug:
            columns: [slug]
