services:
    perform_events.admin.event:
        class: Perform\EventsBundle\Admin\EventAdmin
        tags:
            - { name: perform_base.admin, entity: "PerformEventsBundle:Event" }

    perform_events.menu_link.events:
        class: Perform\EventsBundle\Menu\EventsLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: events }

    perform_events.twig.events:
        class: Perform\EventsBundle\Twig\Extension\EventsExtension
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }
