Perform\BlogBundle\Entity\Post:
    type: entity
    table: perform_blog_post
    repositoryClass: Perform\BlogBundle\Repository\PostRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        title:
            type: string
        slug:
            type: string
            gedmo:
                slug:
                    separator: -
                    fields:
                        - title
        publishDate:
            type: datetime
        content:
            type: text
        enabled:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        tags:
            targetEntity: Perform\BaseBundle\Entity\Tag
            joinTable:
                name: perform_blog_post_tags
            cascade:
                - persist
    uniqueConstraints:
        slug:
            columns: [slug]
