Perform\BlogBundle\Entity\Tag:
    type: entity
    repositoryClass: Perform\BlogBundle\Repository\TagRepository
    table: perform_blog_tags
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: string
    manyToMany:
        posts:
            targetEntity: Post
            mappedBy: tags
    uniqueConstraints:
        name:
            columns: [name]
