Perform\BlogBundle\Entity\Tag:
    type: entity
    table: perform_blog_tags
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: string
    uniqueConstraints:
        name:
            columns: [name]
